/* Frontend-only placeholder copy. Swap for RTK Query hooks when the API exists. */

/** The three legal/marketing pages all ship with the same starter copy. */
export const defaultContent = `
<p>We are a creative digital agency dedicated to helping businesses grow through professional website development, mobile apps, and digital marketing solutions. Our goal is to deliver smart, modern, and results-focused services that help brands build a strong online presence and achieve long-term success.</p>
<p>We specialize in CMS website development using trusted platforms like WordPress, Shopify, Wix, and more. Whether you need a business website, online store, portfolio, blog, or booking platform, we create websites that are visually appealing, mobile-friendly, easy to manage, and optimized for speed and performance. For businesses that need advanced features or unique functionality, we also offer custom website development services. Our team builds secure, scalable, and user-friendly websites tailored to your specific business goals. From startup websites to complex web applications, we turn ideas into high-performing digital solutions.</p>
<p>In addition, we provide mobile app development for Android and iOS. Whether you need an eCommerce app, booking app, service platform, or custom mobile application, we create seamless digital experiences designed for growth. Our digital marketing services help businesses attract more customers and increase sales. We offer SEO, paid ads, social media marketing, branding, and content strategy to improve visibility and generate measurable results.</p>
<p>What sets us apart is our commitment to quality, transparency, and client success. We take time to understand your business and create solutions that truly match your goals. Whether you are a startup, small business, or established company, we are ready to help you grow with powerful digital solutions. From concept to launch, we turn ideas into success.</p>
`.trim();
